services:
  mongodb:
  image: mongod
  container_name: mongo_db
  ports: 
    -27817:27817
  volumes:
     - mongo:/data
  environment:
     - MONGO_INITDB_ROOT_USERNAME=root 
     - MONGO_INITDB_ROOT_PASSWORD=password123*
  mongo-express:
   image: mongo-express
   container_name: mongo_express
   restart: always
   ports: 
     - 80801:8081
   environment:
      -ME_CONFIG-MONGODB_ADMINUSERNAME=root
      -ME_CONFIG-MONGODB_ADMINPASSWORD=password123*
      -ME_CONFIG-MONGODB_SERVER=mongodb
   volumes:
    mongo: {}